# Movie Recommendation System using Content Based Filtering

In [135]:
# importing the libraries

import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings("ignore")

In [136]:
# Read the movies csv files
movies = pd.read_csv("D:\movies.csv")

# Show the first 6 rows of dataset
movies.head(6)

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   
5      5  258000000                  Fantasy Action Adventure   

                                          homepage      id  \
0                      http://www.avatarmovie.com/   19995   
1     http://disney.go.com/disneypictures/pirates/     285   
2      http://www.sonypictures.com/movies/spectre/  206647   
3               http://www.thedarkknightrises.com/   49026   
4             http://movies.disney.com/john-carter   49529   
5  http://www.sonypictures.com/movies/spider-man3/     559   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   
5  dual identity amnesia sandstorm love of one's ...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   
5                              Spider-Man 3   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   
5  The seemingly invincible Spider-Man goes up ag...  115.699814  ...   139.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   
5  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   
5                              The battle within.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   
5                              Spider-Man 3          5.9       3576   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   
5  Tobey Maguire Kirsten D

In [137]:
# number of rows and columns in the data frame
movies.shape

(4803, 24)

In [138]:
# choosing important features which helps to build a movie recommendation system
final_features=["overview","keywords","genres","tagline","cast","director"]

# replacing the null valuess with null string

for feature in final_features:
    movies[feature] = movies[feature].fillna('')

In [139]:
# combining all the 6 selected features

combined_features = movies['genres']+' '+movies['keywords']+' '+movies['overview']+' '+movies['tagline']+' '+movies['cast']+' '+movies['director']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      When ambitious New York attorney Sam is sent...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [140]:
# converting the text data into feature vectors

vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 4288)	0.13213124585063996
  (0, 14180)	0.08418056281586364
  (0, 23134)	0.1498786462809525
  (0, 17784)	0.12285843797047787
  (0, 15569)	0.171366691592621
  (0, 25868)	0.11590870590502833
  (0, 29614)	0.15064979633862852
  (0, 24802)	0.158925784923944
  (0, 23578)	0.16802034155542864
  (0, 30543)	0.15064979633862852
  (0, 30145)	0.18243919685121024
  (0, 23619)	0.11047375838269538
  (0, 19410)	0.0318696249813729
  (0, 30121)	0.07272849549697494
  (0, 9065)	0.14505772980982928
  (0, 5245)	0.16506865163441015
  (0, 1014)	0.12285843797047787
  (0, 1243)	0.05270709034262741
  (0, 21523)	0.1665010643166998
  (0, 1281)	0.03195190270050669
  (0, 19650)	0.1612055740237117
  (0, 10368)	0.13848277654301597
  (0, 2974)	0.09974129089792806
  (0, 27515)	0.14569220419090678
  (0, 2685)	0.09805341831299116
  :	:
  (4802, 27153)	0.05940079357098276
  (4802, 19243)	0.061349419053434766
  (4802, 11941)	0.07829183421073846
  (4802, 29680)	0.07735547381237222
  (4802, 9346)	0.07104321122746965
  (48

In [141]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [142]:
print(similarity.shape)

(4803, 4803)


## Movies Recommendation System

In [150]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : mission impossible


In [151]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [152]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

# finding the index of the movie with title

close_match = find_close_match[0]
index_of_the_movie = movies[movies.title == close_match]['index'].values[0]
print("Index of the movie is {}, and name of inputed movie is {} " .format(index_of_the_movie, close_match))
print("Close matchs of the inputed movie is : ", find_close_match)

Index of the movie is 425, and name of inputed movie is Mission: Impossible 
Close matchs of the inputed movie is :  ['Mission: Impossible', 'Mission: Impossible II', 'Mission: Impossible III']


In [153]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.025634281193337594), (1, 0.05180794060481519), (2, 0.061548679830035986), (3, 0.08021098860298981), (4, 0.036329691460406675), (5, 0.02424333471065224), (6, 0.03701889489365639), (7, 0.0731972359794388), (8, 0.05307655724769584), (9, 0.0314251158742207), (10, 0.052701998614174024), (11, 0.05321256788504417), (12, 0.02880454055066617), (13, 0.03403776752867874), (14, 0.0935265949497451), (15, 0.06647593610324597), (16, 0.040000760326671866), (17, 0.04590353807768427), (18, 0.08877454295050334), (19, 0.04828200440074033), (20, 0.06129003411165427), (21, 0.04379670825688524), (22, 0.03332721876306711), (23, 0.03990573231228273), (24, 0.028715363616940166), (25, 0.036749027978136124), (26, 0.02891204383050336), (27, 0.07167056561497126), (28, 0.024231519529103924), (29, 0.081388394979093), (30, 0.04318341148640198), (31, 0.06513478632392335), (32, 0.04192281896075431), (33, 0.02541808792833442), (34, 0.015151481777821631), (35, 0.034244572906277596), (36, 0.04412326813604756), (37, 

In [154]:
len(similarity_score)

4803

In [155]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(425, 1.0000000000000002), (153, 0.18738270633708748), (213, 0.1838697426818534), (677, 0.1635863854907509), (139, 0.15627576354226816), (737, 0.1491475617329645), (3666, 0.14866011293203474), (884, 0.14229676256342688), (753, 0.1388730470887232), (1701, 0.13790185804900149), (893, 0.13598599855749544), (2583, 0.13381502528830402), (1797, 0.13315175545605232), (622, 0.1330758548943228), (134, 0.13106647026309734), (4339, 0.13100445065089564), (2080, 0.13084412173033325), (372, 0.1261083257952248), (1596, 0.12400925322840566), (1528, 0.12172346667931744), (594, 0.11970714475110213), (392, 0.1171856529611728), (1769, 0.11586846433330654), (611, 0.11554528651771787), (914, 0.11286061190308334), (433, 0.11235492881746251), (2932, 0.11214779712002701), (1973, 0.11044898832386593), (1848, 0.1104272208739996), (1447, 0.10957026195535265), (1077, 0.10923160162845479), (531, 0.10916823467207395), (442, 0.10881193957917135), (1586, 0.10774247125150181), (1279, 0.10576151272852184), (596, 0.1057

In [156]:
# print the name of similar movies based on the index

print('Suggested Movies for you : \n')

i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies[movies.index==index]['title'].values[0]
  if (i<21):
    print(i, '.',title_from_index)
    i+=1

Suggested Movies for you : 

1 . Mission: Impossible
2 . Mission: Impossible - Ghost Protocol
3 . Mission: Impossible II
4 . Clear and Present Danger
5 . Mission: Impossible III
6 . Jack Ryan: Shadow Recruit
7 . Dying of the Light
8 . Zero Dark Thirty
9 . The Sentinel
10 . Once Upon a Time in Mexico
11 . From Paris with Love
12 . The November Man
13 . Agent Cody Banks 2: Destination London
14 . Body of Lies
15 . Mission: Impossible - Rogue Nation
16 . Dr. No
17 . Tinker Tailor Soldier Spy
18 . Spy Game
19 . Sicario
20 . Criminal
